CREATE TABLE Registration (
    courseCode VARCHAR(10) NOT NULL,
    studentEmail VARCHAR(50) NOT NULL,
    registrationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;